### ISSUE TITLE
Some ISPs cause S2I build issues by resolving openshift.example.com

### ISSUE THREAD

**Issue by edseymour** [RedHatEMEA/demobuilder#57] opened 2015-09-05 13:35 UTC
This problem was noticed when connecting to consumer ISP BT Broadband in the UK. 

BT use a service backed by barefruit.co.uk which intercepts unresolvable DNS requests and returns a 'search' page with ads. 

When connecting to this ISP and using a Macbook with VirtualBox, this appears to cause an issue with the S2I build (the nodejs-ex example fails during build). The S2I builder fails during git clone on git://openshift.example.com, unable to connect to the barefruit.co.uk IP returned by the BT router.

**Comment by alberttwong** [comment] 2015-11-20 16:55
I used disconnected my network and used the offline demo and works fine.

**Comment by jim-minter** [comment] 2015-11-27 14:58
@edseymour , would be useful to know if you still see this with the ose 3.1 images and what your advice would be to deal with it

**Comment by jim-minter** [comment] 2016-01-14 10:03
@filippocala I think you're seeing this issue too - infostrada ISP

**Comment by filippocala** [comment] 2016-01-14 10:51
Yes I confirm @jim-minter, with another internet provider the issue is not present.
Thank you.

**Comment by jim-minter** [comment] 2016-01-14 12:48
Another temporary workaround might be to change the DNS settings on the laptop - e.g. using Google's DNS server 8.8.8.8.

**Comment by jim-minter** [comment] 2016-01-18 14:59
And another:

- Do a vagrant destroy ; vagrant up to reset the VM
- In the clean VM, as root, edit /etc/NetworkManager/dispatcher.d/99-hosts so that it reads:

```
#!/bin/bash

if [ "$1" = eth0 -a "$2" = up ]; then
  cat >/etc/hosts <<EOF
# This file is automatically regenerated by $0
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
${IP4_ADDRESS_0%%/*} $(hostname)
EOF

  sed -i -e '/^search / d' /etc/resolv.conf
fi
```

  (all you need to do is add the one sed line above the 'fi')

- Reboot the VM (type 'reboot')
- Now confirm that /etc/resolv.conf only has a comment and a 'nameserver ' line (no 'search ' line(s))
- Try doing a nodejs:0.10 (not nodejs.*-example!) and monster build
- If these don't work, let me now and forward me the output of `sudo journalctl -u atomic-openshift-dns-intercept`)

**Comment by utherp0** [comment] 2016-01-19 07:25
Same issue on GWR Wifi - the script didn't seem to work so I manually ripped out the search line from the resolv.conf and it seems to work fine.

**Comment by jim-minter** [comment] 2016-01-19 21:49
a51f5823de5a2f8d75eebcfa446f92c718c40d17

**Comment by jim-minter** [comment] 2016-02-25 13:42
This should be fixed in the latest release - please LMK if not.

**Closed by jim-minter** 2016-02-25 13:42 UTC
Labels: fixed-pending-release, ose-3.1

**Comment by utherp0** [comment] 2016-02-25 13:57
Just DL'ing the latest image for a demo in a couple of weeks time.

Uth



On Thu, Feb 25, 2016 at 1:42 PM, Jim Minter <notifications@github.com>
wrote:

> This should be fixed in the latest release - please LMK if not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedHatEMEA/demobuilder/issues/57#issuecomment-188789061>
> .
>



-- 
Ian 'Uther' Lawson
Senior Solution Architect
JBoss/Openshift/Infrastructure, Red Hat UK PubSec

E-Mail: ilawson@redhat.com
Mobile: 07803349094

Red Hat UK, 200 Fowler Avenue, Farnborough, Hampshire, GU14 7JP
https://uk.linkedin.com/in/ian-lawson-a0199011
