### ISSUE TITLE
Openshift console uses hostname so on Fedora I had to add a line to /etc/hosts for openshift.example.com to map this to 192.168.121.XXX

### ISSUE THREAD

**Issue by chris-milsted** [RedHatEMEA/demobuilder#104] opened 2015-10-20 19:08 UTC
Just need to doc this I think which I will add to the readme when I figure out how to make a pull request again....

**Comment by jim-minter** [comment] 2015-11-27 14:31
Duplicate of #69

**Closed by jim-minter** 2015-11-27 14:31 UTC
